package com.expenseflow.notification.domain.valueobject;

public enum NotificationType {
    EXPENSE_POSTED,
    SETTLEMENT_GENERATED,
    SETTLEMENT_CONFIRMED,
    SETTLEMENT_DISPUTED,
    USER_ADDED,
    BUDGET_LIMIT_EXCEEDED,
    BUDGET_WARNING,
    RECURRING_EXECUTION,
    RECURRING_EXECUTION_FAILED,
    SAVINGS_GOAL_COMPLETED
}
