spring:
  profiles:
    active: dev
  application:
    name: ExpenseFlow
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    time-zone: UTC

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# Actuator Config
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

# OpenAPI Config
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
