package com.expenseflow.settlement.domain.entity;

import com.expenseflow.entity.BaseEntity;
import com.expenseflow.expense.domain.valueobject.Money;
import com.expenseflow.settlement.domain.valueobject.SettlementStatus;
import com.expenseflow.settlement.exception.InvalidSettlementStateException;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Settlement Aggregate Root.
 *
 * Represents a single debt obligation between two group members.
 * Generated by the DebtMinimizationSolver from POSTED expense splits.
 *
 * State Machine (ADR-005 §8.2):
 *   PENDING  → CONFIRMED  (debtor confirms payment)
 *   PENDING  → DISPUTED   (creditor raises dispute)
 *   DISPUTED → CONFIRMED  (dispute resolved)
 *
 * Optimistic locking via @Version prevents concurrent modification conflicts.
 * Extends BaseEntity to inherit audit properties (createdAt, updatedAt, isDeleted, etc.).
 */
@Entity
@Table(name = "settlements")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SettlementEntity extends BaseEntity {

    @Id
    @Column(name = "id", length = 36, nullable = false)
    private String id;

    /** Parent group — referenced by ID only (ADR-005 §5.3) */
    @Column(name = "group_id", length = 36, nullable = false)
    private String groupId;

    /** Parent trip — nullable; present only for trip-scoped settlements */
    @Column(name = "trip_id", length = 36)
    private String tripId;

    /** The user who owes money (debtor) */
    @Column(name = "from_user_id", length = 36, nullable = false)
    private String fromUserId;

    /** The user who is owed money (creditor) */
    @Column(name = "to_user_id", length = 36, nullable = false)
    private String toUserId;

    @Embedded
    private Money money;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", length = 20, nullable = false)
    @Builder.Default
    private SettlementStatus status = SettlementStatus.PENDING;

    /** Optional note / resolution notes */
    @Transient
    private String note;

    /** Timestamp when status transitioned to CONFIRMED */
    @Column(name = "settled_at")
    private LocalDateTime settledAt;

    /** Optimistic locking — prevents concurrent modification (ADR-005 §3.8) */
    @Version
    @Builder.Default
    @Column(name = "version", nullable = false)
    private Long version = 0L;

    /**
     * Append-only history log.
     * All status transitions are recorded here automatically via transitionTo().
     */
    @OneToMany(mappedBy = "settlement", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<SettlementHistoryEntity> history = new ArrayList<>();

    // ─────────────────────────────────────────────────────────────────────────
    // Aggregate Behaviour
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Transitions this settlement to a new status, enforcing the permitted
     * state machine (ADR-005 §8.2). Appends a SettlementHistoryEntity entry.
     *
     * @param newStatus  The target status.
     * @param actorId    The user ID initiating the transition.
     * @param note       Optional note (e.g. dispute reason).
     * @throws InvalidSettlementStateException if the transition is not permitted.
     */
    public void transitionTo(SettlementStatus newStatus, String actorId, String note) {
        validateTransition(newStatus);

        SettlementStatus previous = this.status;
        this.status = newStatus;
        this.setUpdatedBy(actorId);
        this.setUpdatedAt(LocalDateTime.now());

        if (newStatus == SettlementStatus.CONFIRMED) {
            this.settledAt = LocalDateTime.now();
        }

        this.history.add(SettlementHistoryEntity.builder()
                .id(java.util.UUID.randomUUID().toString())
                .settlement(this)
                .fromStatus(previous.name())
                .toStatus(newStatus.name())
                .changedBy(actorId)
                .note(note)
                .build());
    }

    /**
     * Updates the settlement amount in place (used during idempotent re-generation).
     * Only PENDING settlements may have their amount updated.
     */
    public void updateAmount(Money newMoney, String actorId) {
        if (this.status != SettlementStatus.PENDING) {
            throw new InvalidSettlementStateException(
                    "Cannot update amount of a " + this.status + " settlement. " +
                    "Only PENDING settlements may be recalculated.");
        }
        this.money = newMoney;
        this.setUpdatedBy(actorId);
        this.setUpdatedAt(LocalDateTime.now());
    }

    /**
     * Validates that the requested status transition is permitted by the
     * settlement state machine (ADR-005 §8.2).
     */
    private void validateTransition(SettlementStatus newStatus) {
        boolean allowed = switch (this.status) {
            case PENDING  -> newStatus == SettlementStatus.CONFIRMED || newStatus == SettlementStatus.DISPUTED;
            case DISPUTED -> newStatus == SettlementStatus.CONFIRMED;
            case CONFIRMED -> false;
        };

        if (!allowed) {
            throw new InvalidSettlementStateException(
                    "Invalid transition: " + this.status + " → " + newStatus +
                    ". See ADR-005 §8.2 for permitted transitions.");
        }
    }
}
